>P1;1neu00
Domain2 aligned sequence - pima
IVVYTDREVYGAVGSQVTLHCSFWSSEWVSDDISFTWRYQ-PEGGRDAISIFHYAKGQPYIDEVGTFKERIQWVGDPSWKDGSIVIHNLDYSDNGTFTCDV---------KNVGKTSQVTLYVFE*
>P1;12e8H1
Domain1 aligned sequence - pima
-EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLEWIGWIDP--EIGDTEYVPKFQGKATMTADTSSNTAYLQLSSLTSEDTAVYYCNAGHDYDRGRFPYWGQGTLVTVSA--*
