>P1;1neu00
Sequence extracted from PDB file - By pdb2pir
-IVVYTDREVYGAVGSQVTLHCSFWSSEWVSDDISFTWRYQPEGGRDAISIFHYAKG--QPYIDEVGTFKERIQWVGDPSWKDGSIVIHNLDYSDNGTFTCDVKN-------VGKTSQVTLYVF-*
>P1;12e8H1
Sequence extracted from PDB file - By pdb2pir
EVQLQQSGAEVVRSGASVKLSCTASGF--NIKDYYIHWVKQRPEK-GLEWIGWIDPEIGDTEYVPK--FQGKATMTADTSSNTAYLQLSSLTSEDTAVYYCNAGHDYDRGRFPYWGQGTLVTVSA*


